spring.application.name=WigellMcRental
spring.datasource.url=jdbc:mysql://localhost:3306/wigell_mc_db
spring.datasource.username=root
spring.datasource.password=Coolspot123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

